### ISSUE TITLE
Guzzle build_query() Error

### ISSUE THREAD

**Issue by claytonk** [sepiariver/auth0#7]
Just installed 1.3.4 and am getting the following error during the authentication process:

`Call to undefined function GuzzleHttp\Psr7\build_query() in /...core/components/auth0/model/vendor/auth0/auth0-php/src/API/Authentication.php:158`

From what I understand, build_query() has been deprecated as of Guzzle 7.2 and replaced with Query::build. 

PS. Sorry I haven't gotten back to you on the v2 testing, I wasn't able to access the scope settings for the site I was testing on (I don't control the Auth0 account for that site) so I couldn't get it to work. I'll set up another test site as soon as I can and get back to you.

**Comment by claytonk** [comment]
Just to confirm, I replaced line 158 with `Psr7\Query::build($params)` and it works.

**Comment by sepiariver** [comment]
Thanks @claytonk this is fixed in 1.3.5
